### ISSUE TITLE
Cannot compile master or 0.6.3

### ISSUE THREAD

**Issue by darkman7hr** [HASwitchPlate/openHASP#556] opened 2023-10-09 12:45 UTC
Is it new platformio or? In what version of platformio/code do you compile?
0.6.2 Compiles just fine.

`Compiling .pio/build/az-touch-mod-esp32_ili9341_4MB/src/hasp/hasp_font.cpp.o
Compiling .pio/build/az-touch-mod-esp32_ili9341_4MB/src/hasp/hasp_lvfs.cpp.o
src/hasp/hasp_font.cpp:14:10: fatal error: ft2build.h: No such file or directory

******************************************************************
* Looking for ft2build.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ft2build.h"
* Web  > https://registry.platformio.org/search?q=header:ft2build.h
*
******************************************************************

 #include "ft2build.h"  // for FT_FREETYPE_H macro
          ^~~~~~~~~~~~
compilation terminated.
*** [.pio/build/az-touch-mod-esp32_ili9341_4MB/src/hasp/hasp_font.cpp.o] Error 1`

**Comment by fvanroie** [comment] 2023-10-09 14:01
Duplicate of #405

**Closed by fvanroie** 2023-10-09 14:01 UTC
Labels: bug
