### ISSUE TITLE
Any chance we can it work for another esp32-s3 GT911 touch display (ESP32-4848S040)

### ISSUE THREAD

**Issue by mswaleh** [HASwitchPlate/openHASP#603] opened 2024-01-02 09:37 UTC
I found this cheap display at Aliexpress (https://www.aliexpress.us/item/1005006334976806.html) which appears to be new(er) in the market.

Board: ESP32-S3-N16R8
Display: ST7701, Touch: GT911

This is very close to "GS-T3E v2.3" in specs, which is one from the nightly list (https://nightly.openhasp.com/).

I am able to install it, it even connect to WiFi AP and then to my WiFi via the webUI. I can also see screenshot in the web UI but nothing comes on screen. I was trying to look at the source code but quite new to all this. Anybody can point me right direction or help with this, would be greatly appreciated.

**Comment by tbxMb** [comment] 2024-01-02 18:59
I also have one of these and i managed to setup the pin configuration for the Display.
I got the pin mappings out of the `1-Demo/Demo_Arduino/1_1_86switch_onoff/86switch_onoff/86switch_onoff.ino` sketch provided with the units documentation.

Everything seems to work except the colors. 
![image](https://github.com/HASwitchPlate/openHASP/assets/46108034/8b4712ca-8b57-4312-aa98-551f1cc27b18)
![expected-1](https://github.com/HASwitchPlate/openHASP/assets/46108034/c57ad916-c3de-4078-ad85-44ed101b42fa)

![testimage-image](https://github.com/HASwitchPlate/openHASP/assets/46108034/1ae1bad8-8ed8-4576-8643-b95965bdea82)
![expected-2](https://github.com/HASwitchPlate/openHASP/assets/46108034/93efce26-f91f-449a-bc93-c593f1c9b3e2)

**Comment by mswaleh** [comment] 2024-01-02 19:46
wow, that was fast. thanks. I saw and copied your changes. I am also trying to figure out to see if there is anything I can do to make it work. I will share here. I like this display. Couple of binaries they have for demo, work really well. hoping to get it to work like it does in the demos.

**Comment by cleverhomeKK** [comment] 2024-01-02 21:57
Hi, I have the same problem. One more thing, if it helps with the search: It will be red at: #00FFFF
instead of #FF0000 . Seems somehow negated.

**Comment by tbxMb** [comment] 2024-01-02 22:51
Here are some tests. The image indeed gets displayed with inverted colors. When inverting the photo of the display in Gimp everything looks Ok.
![compi](https://github.com/HASwitchPlate/openHASP/assets/46108034/237adfea-cd70-4966-a682-0be4307133b8)

I tried to enable the Invert option in the display settings but that does not work.

**Comment by mswaleh** [comment] 2024-01-02 23:07
@tbxMb great job.
It appears, inverted colors are closer to the original. by the way, can you share the env entries you made to make it work. I am trying to build it on another repo (https://github.com/mswaleh/msopenHASP) but my job is failing because of "
UnknownEnvNamesError: Unknown environment names 'esp32-s3-4848s050'".

**Comment by tbxMb** [comment] 2024-01-02 23:16
I think you got a typo there its `esp32-s3-4848s040`

**Comment by mswaleh** [comment] 2024-01-02 23:18
ha. literally saw seconds before your comment :-D. Much appreciated

**Comment by tbxMb** [comment] 2024-01-02 23:31
I manually enabled the hardware invert function via a spi write and managed to get the primary colors looking alright. But gradients still look weird. 
![compi_gradient](https://github.com/HASwitchPlate/openHASP/assets/46108034/1f652c61-ae42-4cd6-9ea7-327d56b802a3)
Im not sure what is causing this but i think i have seen something like once.

**Comment by tbxMb** [comment] 2024-01-03 01:47
### ITS WORKING 🥳

![working](https://github.com/HASwitchPlate/openHASP/assets/46108034/e305d3c1-fbd9-40f4-a58c-585be9a6da6d)

I had to change one byte in the setup operations from 0x08 to 0x00, i also merged the display invert command into the setup operations.

Can someone validate that it is also working on their device ?

**Comment by mswaleh** [comment] 2024-01-03 02:01
@tbxMb can you link the artifacts file?

**Comment by tbxMb** [comment] 2024-01-03 02:31
@mswaleh i cant link you one, but here is the commit that you can build yourself :) 

[7af48cf](https://github.com/tbxMb/openHASP/commit/7af48cff375fc0c73ffa10230f0dc45a7c1a2354)

**Comment by mswaleh** [comment] 2024-01-03 04:42
I can confirm that it is working smoothly. saweeet.. great job @tbxMb

**Comment by smcgann99** [comment] 2024-01-10 15:48
This looks really nice for the price. 
Can you confirm the spec, web site is a bit lacking, it seems to have battery input 3 x relays I assume a 240V PSU built in etc ....

**Comment by cleverhomeKK** [comment] 2024-01-10 23:17
Hi,
The device has a 230V power supply (and USB-C on the side) and 1-3 relay outputs (230V).
These can of course also be controlled by OpenHasp.
However, the back part :-) does not fit into a round EU flush-mounted box.

**Comment by smcgann99** [comment] 2024-01-11 02:24
> Hi, The device has a 230V power supply (and USB-C on the side) and 1-3 relay outputs (230V). These can of course also be controlled by OpenHasp. However, the back part :-) does not fit into a round EU flush-mounted box.

Any chance you could post some pictures of the back of the case ? 
Its very similar to the GS-T3E v2.3, but MUCH cheaper

**Comment by mswaleh** [comment] 2024-01-11 02:38
It works with 110V too. 3 ways you can power it, USB-C, GPIO pins (5v and gnd), and AC. I think it can take 110-250VAC.

**Comment by fduch2k** [comment] 2024-01-11 04:30
works like a charm on my esp32-4848S040 device. No glitches, no color issues. Thank you

**Comment by smcgann99** [comment] 2024-01-11 11:26
Just checked the download link on product page an its actually a TFT screen not IPS ;-(

**Comment by RednazPublic** [comment] 2024-01-14 18:27
![20240114_142400](https://github.com/HASwitchPlate/openHASP/assets/50893672/f469ead9-8ddc-40dd-81df-793e152a217d)
![20240114_142537](https://github.com/HASwitchPlate/openHASP/assets/50893672/cb65a7c8-49ad-4e90-88bd-ddf49e5e78d4)
![20240114_142543](https://github.com/HASwitchPlate/openHASP/assets/50893672/76bacb4b-2dd7-4948-9cf4-bf638ec46df0)
![20240114_142707](https://github.com/HASwitchPlate/openHASP/assets/50893672/54582ab9-f8fd-4ccc-8e10-f2ec6c670732)
![20240114_142714](https://github.com/HASwitchPlate/openHASP/assets/50893672/b8dbe8d6-4d17-48b6-94fe-c067c0ff57b4)
![20240114_142733](https://github.com/HASwitchPlate/openHASP/assets/50893672/3114451d-d3f3-471d-a2de-bf72141be281)
![20240114_142921](https://github.com/HASwitchPlate/openHASP/assets/50893672/95bfd8a6-ca79-4ce4-b277-7b6376334b8e)
![Apresentação1](https://github.com/HASwitchPlate/openHASP/assets/50893672/90f68190-cbfc-4672-9b7b-11466e5ee70a)
![20240114_143001](https://github.com/HASwitchPlate/openHASP/assets/50893672/17fea3e8-897f-40e2-9552-1565b9f9a7a3)
![20240114_143039](https://github.com/HASwitchPlate/openHASP/assets/50893672/9a214ba3-b965-4aaa-b451-8c2fad8723dd)

**Comment by RednazPublic** [comment] 2024-01-14 18:41
I hope it can help. The board description image has yellow circles and these are zero ohm resistors, the connection between the boards (where I left "?") are L1, L2 and L3. I made a mistake, the correct digital audio is NS4168 and the 4 inch display relay and I2S audio are shared IO ports, IO1, IO2 and IO40. If audio is required, 0 ohm resistors R25, R26 and R27 must be moved to R21, R22 and R23.

**Comment by smcgann99** [comment] 2024-01-15 02:17
> I hope it can help. The board description image has yellow circles and these are zero ohm resistors, the connection between the boards (where I left "?") are L1, L2 and L3. I made a mistake, the correct digital audio is NS4168 and the 4 inch display relay and I2S audio are shared IO ports, IO1, IO2 and IO40. If audio is required, 0 ohm resistors R25, R26 and R27 must be moved to R21, R22 and R23.

Thanks very much for this. What is the picture quality / viewing angle like with it being a TFT ?
Have noticed any ghosting (screen burn etc), that has been reported on cheaper displays ?

**Comment by tbxMb** [comment] 2024-01-15 12:24
Id say the Image quality is really good, and the viewing angles too you can look at it from almost 90° it gets a bit darker but is still legible. As for burn in i haven't had time to use it longer than a few hours but i did not really notice any Burn In yet.

**Comment by RednazPublic** [comment] 2024-01-15 13:05
> Thanks very much for this. What is the picture quality / viewing angle like with it being a TFT ? Have noticed any ghosting (screen burn etc), that has been reported on cheaper displays ?

I'm sorry, it arrived last Friday and I was just checking the board and connection, I didn't really use it for over an hour. I'm actually going to use it for another project and saw your request for photos.

**Comment by teoconnect** [comment] 2024-02-10 10:41
Very good device, all works for me too, the display is also very good
thank's for your hard work

it's possible to include the device in the nightly build?
https://nightly.openhasp.com/
![image](https://github.com/HASwitchPlate/openHASP/assets/48184577/b9e5ed7e-0c29-4000-8f1d-bbf39510bcba)

**Comment by fvanroie** [comment] 2024-02-10 12:32
> it's possible to include the device in the nightly build?

Please provide a Pull request with the ini file for this device.

**Comment by teoconnect** [comment] 2024-02-10 15:23
I meant the portal https://nightly.openhasp.com/
where currently the entry for esp32-s3-4848s040 is missing,
in the .ini file configuration is already present, just select the 2 entries below
     user_setups/esp32s3/*.ini
     esp32-s3-4848S040
with this selection the device work propertly

**Comment by kipwittchen** [comment] 2024-02-19 14:25
I recently purchased this device and am anticipating its arrival! Pardon my ignorance, where would the pull request be made to get this board added to the nightly build portal? I see the html file that lists the boards: https://github.com/fvanroie/install/blob/main/html/index.html but that doesn't seem to link to the platformio_override.ini file to uncomment the two lines necessary?

**Comment by Aleborg** [comment] 2024-02-26 17:19
> Very good device, all works for me too, the display is also very good
> thank's for your hard work
> 
> it's possible to include the device in the nightly build?
> https://nightly.openhasp.com/
> ![image](https://github.com/HASwitchPlate/openHASP/assets/48184577/b9e5ed7e-0c29-4000-8f1d-bbf39510bcba)
> 
> below the link of the build that i have installed
> https://www.dropbox.com/scl/fi/emfuptraro12qfbw6albs/esp32-s3-4848S040_full_16MB_v0.7.0-rc9_2dce5da.bin?rlkey=xkk4w8g3gxujltxq4mzptnfgo&dl=0

Awesome, thanks, works perfect for me!
Does anyone know if it's possible to use the built in bluetooth as a proxy fof HA?

**Comment by fvanroie** [comment] 2024-02-26 18:36
> Does anyone know if it's possible to use the built in bluetooth as a proxy fof HA?

openHASP does not support bluetooth  as a proxy. You have to use another firmware or another device for that.

**Comment by Aleborg** [comment] 2024-02-27 06:53
@fvanroie thanks for the quick reply!
A pity but understandable given that it can interfere with the wifi!

**Comment by fvanroie** [comment] 2024-03-02 23:54
> I meant the portal https://nightly.openhasp.com/ where currently the entry for esp32-s3-4848s040 is missing, in the .ini file configuration is already present,

The device has been added to nightly, please test if you have the chance.

**Comment by flexiti** [comment] 2024-03-03 14:34
I confirm that the anESP32-4848S040 compilation works, the custom option also works fine. **Thanks for this.** 
Does anyone have an electrical diagram for this model?

**Comment by flexiti** [comment] 2024-03-03 14:40
According to me, here is NS4168 (not NS4188 as commented in description photo above) - 2.5W audio I2S, how can we use it?

**Comment by flexiti** [comment] 2024-03-09 12:22
Switch SW1 is connected to pin 5 IP5306, It disconnects the power (actually acts as a reset) if you hold it for 10 seconds

**Comment by flexiti** [comment] 2024-03-09 12:26
Yellow resistor on the right, its on/off power supply from USB, yellow on the right - disconnect backlight from the port IO38

**Comment by flexiti** [comment] 2024-03-09 17:09
Sensor DS18B20,AHT20,BMP280 are working

![ESP32_view1](https://github.com/HASwitchPlate/openHASP/assets/11538048/721b5a04-8a78-4e35-b028-503a707a480c)

**Comment by xiasi0** [comment] 2024-03-10 12:41
> ESP32-4848S040 本地连接传感器 - DS18B20、AHT20、BMP280 正在工作
> 
> ![ESP32_view1](https://private-user-images.githubusercontent.com/11538048/311454964-721b5a04-8a78-4e35-b028-503a707a480c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwNzQ1NzMsIm5iZiI6MTcxMDA3NDI3MywicGF0aCI6Ii8xMTUzODA0OC8zMTE0NTQ5NjQtNzIxYjVhMDQtOGE3OC00ZTM1LWIwMjgtNTAzYTcwN2E0ODBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDEyMzc1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NjJjNGU2NDg2MGU5ZmMxNWNkYzNjYjJiNTAzYzRiYmI1OGRkZjY4ZTllMWQwZmNiYmZjOGRiYjUwYzNkMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AWWmQRmSRnqEQPLipT6HChwrwyafVvMJQtIrKR30QBY)


Is the backlight brightness of ESP32-4848S040 unable to be adjusted? I tried adjusting the brightness and it would directly turn off the backlight

**Comment by fvanroie** [comment] 2024-03-10 13:26
> Is the backlight brightness of ESP32-4848S040 unable to be adjusted? I tried adjusting the brightness and it would directly turn off the backlight

Please try https://github.com/HASwitchPlate/openHASP/actions/runs/8222316763

**Comment by xiasi0** [comment] 2024-03-10 14:12
> > ESP32-4848S040 的背光亮度是无法调节的吗？我尝试调整亮度，它会直接关闭背光
> 
> 请尝试 https://github.com/HASwitchPlate/openHASP/actions/runs/8222316763

This firmware esp32-s3-4848s040'full_16MB_v0.7.0-rc11'f27744b still turns off the backlight completely when the backlight brightness is around 80%.

**Comment by xiasi0** [comment] 2024-03-10 14:51
> > > ESP32-4848S040 的背光亮度是无法调节的吗？我尝试调整亮度，它会直接关闭背光
> > 
> > 
> > 请尝试 https://github.com/HASwitchPlate/openHASP/actions/runs/8222316763
> 
> 当背光亮度在 80% 左右时，该固件 esp32-s3-4848s040'full_16MB_v0.7.0-rc11'f27744b 仍会完全关闭背光。

IO1, IO2, IO40 correspond to three relays. IO1 and IO2 are working normally. IO40 has no 3.3V output and no corresponding output. Please review

**Comment by fvanroie** [comment] 2024-03-10 16:46
> This firmware esp32-s3-4848s040'full_16MB_v0.7.0-rc11'f27744b still turns off the backlight completely when the backlight brightness is around 80%.

Can you try adding     -D BACKLIGHT_FREQUENCY=2000  to the config?
The default is 20000, maybe that's too much for those boards

**Comment by kipwittchen** [comment] 2024-03-10 17:23
> Sensor connected locally to ESP32-4848S040 - DS18B20,AHT20,BMP280 are working
> 
> ![ESP32_view1](https://private-user-images.githubusercontent.com/11538048/311454964-721b5a04-8a78-4e35-b028-503a707a480c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwOTE2NTIsIm5iZiI6MTcxMDA5MTM1MiwicGF0aCI6Ii8xMTUzODA0OC8zMTE0NTQ5NjQtNzIxYjVhMDQtOGE3OC00ZTM1LWIwMjgtNTAzYTcwN2E0ODBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEwVDE3MjIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNjkwYTdjNWZkNGY1NDYzM2NmMjg2ZTJhN2RmNTMzM2JjZGQ5MjgxMGEzZjE5ZmE2ODllMWZiZDZjMTRlNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nrWYusR2kYs0RVcFIqlHeKcsMhpLD8lvCJ9MaQJpbrY)

What GPIO settings or config did you use to access these sensors?

**Comment by flexiti** [comment] 2024-03-10 17:51
https://github.com/HASwitchPlate/openHASP/discussions/666
I2C 
https://github.com/HASwitchPlate/openHASP/discussions/664
Port 1

**Comment by flexiti** [comment] 2024-03-10 18:56
> Can you try adding -D BACKLIGHT_FREQUENCY=2000 to the config?
> The default is 20000, maybe that's too much for those boards
@fvanroie
I changed it and tried - PWM backlight working on this board with these settings (2000)

**Comment by kipwittchen** [comment] 2024-03-10 19:46
> > Can you try adding -D BACKLIGHT_FREQUENCY=2000 to the config?
> > The default is 20000, maybe that's too much for those boards
> > @fvanroie
> > I changed it and tried - PWM backlight working on this board with these settings (2000)

Also can confirm this works! Though anything below 25% is too dark to see.

**Comment by kipwittchen** [comment] 2024-03-10 23:00
> @kipwittchen #666 I2C #664 Port 1

Thanks! For some reason I can't seem to get it to read values in but I'll keep plugging away. I'm trying to get it to publish the values via mqtt so may be my modifications causing the issue

**Comment by xiasi0** [comment] 2024-03-11 15:15
> > This firmware esp32-s3-4848s040'full_16MB_v0.7.0-rc11'f27744b still turns off the backlight completely when the backlight brightness is around 80%.
> 
> Can you try adding -D BACKLIGHT_FREQUENCY=2000 to the config? The default is 20000, maybe that's too much for those boards



> > This firmware esp32-s3-4848s040'full_16MB_v0.7.0-rc11'f27744b still turns off the backlight completely when the backlight brightness is around 80%.
> 
> Can you try adding -D BACKLIGHT_FREQUENCY=2000 to the config? The default is 20000, maybe that's too much for those boards

It's normal now, thank you

**Comment by xiasi0** [comment] 2024-03-11 15:42
![1710171593112](https://github.com/HASwitchPlate/openHASP/assets/129178072/f28ed9cd-ffa4-44cd-9119-073431ab0a20)

I haven't set up GPIO, what are these entities? Can I not compile this part of the entity?

**Comment by xiasi0** [comment] 2024-03-11 15:53
> > > @fvanroie
> > > I changed it and tried - PWM backlight working on this board with these settings (2000)
> 
> i'm new to openhasp, but where do i add that? (-D BACKLIGHT_FREQUENCY=2000) thank

![1710172200309](https://github.com/HASwitchPlate/openHASP/assets/129178072/4c85bb4b-104e-4670-9dab-6e06f69dc7a1)

Find it here, but be careful, I'll lower the frequency. Will cause abnormal noise in the MOS tube. Similar to electric current sound. This is inevitable to reduce frequency.

**Comment by kipwittchen** [comment] 2024-03-11 15:56
> @kipwittchen #666 I2C #664 Port 1

Hope this isn't a dumb question, are these sensors actually on the board or did you wire them yourself to the board?

**Comment by RealDeco** [comment] 2024-03-11 16:38
> Find it here, but be careful, I'll lower the frequency. Will cause abnormal noise in the MOS tube. Similar to electric current sound. This is inevitable to reduce frequency.

ok i had hoped for a more userfriendly place, i'm not a developer so i'll just sit quiet and pray that someone hopefully fix that in the future :)) 

thanks for the answer anyway

**Comment by fvanroie** [comment] 2024-03-11 17:01
No need to sit back and wait, try out the [latest build from Actions](https://github.com/HASwitchPlate/openHASP/actions/runs/8234155942) and test that. If it works fine please report and I'll update the nightly installer.

**Comment by RealDeco** [comment] 2024-03-11 17:43
> No need to sit back and wait, try out the [latest build from Actions](https://github.com/HASwitchPlate/openHASP/actions/runs/8234155942) and test that. If it works fine please report and I'll update the nightly installer.

wow nice! that fixed the backlight, but the "short idle" in config settings sets it to 10% where it's not visible, 50% would be better, is there a place to edit that?

thanks for quick reply 👍

**Comment by xiasi0** [comment] 2024-03-11 18:00
\



> No need to sit back and wait, try out the [latest build from Actions](https://github.com/HASwitchPlate/openHASP/actions/runs/8234155942) and test that. If it works fine please report and I'll update the nightly installer.



> No need to sit back and wait, try out the [latest build from Actions](https://github.com/HASwitchPlate/openHASP/actions/runs/8234155942) and test that. If it works fine please report and I'll update the nightly installer.

The GPIO40 setting relay is not available. May I ask how to cancel compilation for useless entities

**Comment by xiasi0** [comment] 2024-03-11 18:06
\



> No need to sit back and wait, try out the [latest build from Actions](https://github.com/HASwitchPlate/openHASP/actions/runs/8234155942) and test that. If it works fine please report and I'll update the nightly installer.



> No need to sit back and wait, try out the [latest build from Actions](https://github.com/HASwitchPlate/openHASP/actions/runs/8234155942) and test that. If it works fine please report and I'll update the nightly installer.

The GPIO40 setting relay is not available. May I ask how to cancel compilation for useless entities

**Comment by kipwittchen** [comment] 2024-03-11 18:29
> > No need to sit back and wait, try out the [latest build from Actions](https://github.com/HASwitchPlate/openHASP/actions/runs/8234155942) and test that. If it works fine please report and I'll update the nightly installer.
> 
> wow nice! that fixed the backlight, but the "short idle" in config settings sets it to 10% where it's not visible, 50% would be better, is there a place to edit that?
> 
> thanks for quick reply 👍
> 
> edit: it works i can now change brightness smooth, but under 35 it's like off.

Are you using the home assistant integration? It the backlight % at idle can be adjusted under settings there.

**Comment by RealDeco** [comment] 2024-03-11 18:36
> Are you using the home assistant integration? It the backlight % at idle can be adjusted under settings there.

yeah, it's from home assistant i can see that under 35% the display is like off, so the "short idle" settings at 10% is same as off, but i can now adjust backlight more smoothly, before it was line on/off at 85%

**Comment by RealDeco** [comment] 2024-03-12 14:54
i just noticed something i didn't notice before, when backlight is anything ELSE than 100% the display makes a  constant ringing tone, but not when at 100%, could it be the freq at 2000 causing this?

**Comment by RealDeco** [comment] 2024-03-13 14:24
> hello, does anyone have a bin file available with some background image

you can make one here: https://lvgl.io/tools/imageconverter

**Comment by tiimsvk** [comment] 2024-03-13 14:26
I tested and the problem will be in esphome code

**Comment by xiasi0** [comment] 2024-03-14 03:31
> i just noticed something i didn't notice before, when backlight is anything ELSE than 100% the display makes a constant ringing tone, but not when at 100%, could it be the freq at 2000 causing this?

Yes, a frequency of 2000 is a sound that can be heard by the ears. Adjust the frequency to 20000, and if the frequency is not within the range of ear hearing, you will not be able to hear.

**Comment by tiimsvk** [comment] 2024-03-14 03:47
> > I tested and the problem will be in esphome code
> 
> i think the support for this display is still experimental on exphome (last time i checked), but isn't this the wrong place to ask?, this is about OpenHASP which actually works quite well

Of course, my questions are primarily aimed at the esphome community. But I only needed to verify on another platform, which I do not know how to program, whether the display is functional or it was confirmed.

**Comment by Tall-Paul** [comment] 2024-03-14 10:59
Hi, I'm new to openHasp so please excuse me if I'm being stupid.... should I just be able to install from the nightly builds, using the 'Guition ESP32-S3-4848S040' option and have it work now?

Because I get the wifi setup, reboot and see an IP address on screeen but then don't get anything else other than the image shown.

Uploading a jsonl from the home assistant integration also doesn't seem to work (I can connect to the devices CLI from the build installer webpage and set the mqtt details to integrate with home assistant)
![PXL_20240314_105649215](https://github.com/HASwitchPlate/openHASP/assets/600126/54117368-bd3f-4730-8af4-eee723ed8c2a)

**Comment by kipwittchen** [comment] 2024-03-14 11:11
Yes! I will say it's a bit strange to get used to the flow process at first, you can edit the plates file through the web interface file Editor or the home assistant interface (make sure you're putting the file in the correct place and you've given permission to HA to read that folder). The file used by the HA integration overwrites the one on the device once it's connect via mqtt.

**Comment by Tall-Paul** [comment] 2024-03-14 11:35
There isn't a web interface!  After connecting to wifi all I see is the blank screen with the hostname in the top left corner both before and after connecting to home assistant.

**Comment by flexiti** [comment] 2024-03-14 11:51
> > @kipwittchen #666 I2C #664 Port 1
> 
> Hope this isn't a dumb question, are these sensors actually on the board or did you wire them yourself to the board?

![zd3](https://github.com/HASwitchPlate/openHASP/assets/11538048/b9820bba-c13d-4414-af98-f44831ea2311)

**Comment by kipwittchen** [comment] 2024-03-14 11:57
> There isn't a web interface! After connecting to wifi all I see is the blank screen with the hostname in the top left corner both before and after connecting to home assistant.

Do you get an IP address that pops up when you first turn on the device? That's the address of the device and web interface

**Comment by Tall-Paul** [comment] 2024-03-14 12:20
> > There isn't a web interface! After connecting to wifi all I see is the blank screen with the hostname in the top left corner both before and after connecting to home assistant.
> 
> Do you get an IP address that pops up when you first turn on the device? That's the address of the device and web interface

Oh my god, I'm an idiot.

Yes, there's an IP and yes I get the web interface when I connect to it.  I'm an idiot, thank you!

**Closed** 2024-03-14 15:38 UTC
Labels: enhancement, hardware, done

**Comment by RealDeco** [comment] 2024-03-14 15:49
i noticed this been closed as completed now?, i had hoped there was still a solution for the freq noise?

**Comment by kipwittchen** [comment] 2024-03-14 16:35
> i noticed this been closed as completed now?, i had hoped there was still a solution for the freq noise?

Someone needs to experiment with different frequencies probably?

**Comment by Suschibomber** [comment] 2024-04-09 19:04
Hi guys, I find the project exciting and we have now bought a house and I would like to distribute a few of these displays in the rooms. I don't know if my question is right here, but I didn't know where else.

OpenHasp is completely new territory for me. HomeAssistant is running and I've already got an NSPanel Pro running with HomeAssistant.

Now I have two or three questions. How is the performance of the devices compared to the NSPanel Pro? How much effort does it take to integrate them into HomeAssistant? And would someone perhaps be willing to help me for a fee if I decide to buy some of them?

Best regards and many thanks in advance.

https://de.aliexpress.com/item/1005006348529558.html?spm=a2g0o.productlist.0.0.55432ysd2ysdtA&mp=1&gatewayAdapt=glo2deu

**Comment by TNTLarsn** [comment] 2024-04-11 08:00
> Hi guys, I find the project exciting and we have now bought a house and I would like to distribute a few of these displays in the rooms. I don't know if my question is right here, but I didn't know where else.
> 
> OpenHasp is completely new territory for me. HomeAssistant is running and I've already got an NSPanel Pro running with HomeAssistant.
> 
> Now I have two or three questions. How is the performance of the devices compared to the NSPanel Pro? How much effort does it take to integrate them into HomeAssistant? And would someone perhaps be willing to help me for a fee if I decide to buy some of them?
> 
> Best regards and many thanks in advance.
> 
> https://de.aliexpress.com/item/1005006348529558.html?spm=a2g0o.productlist.0.0.55432ysd2ysdtA&mp=1&gatewayAdapt=glo2deu

I managed to get this working with homeassistant. It is very responsive and I'm quite satisfied with the result.
I implemented some custom jinja-Templates to generate a simple grid-System, so you don't have to count the pixels anymore. To get some help I suggest, opening a new topic in the [HA user Forums](https://community.home-assistant.io/) because this is related to the development of openhasp firmware. 
@Suschibomber You may send me the link to your HA-Forums-Topic and we continue there

![screenshot](https://github.com/HASwitchPlate/openHASP/assets/5354495/d9d215b4-14ad-40c3-b70c-d8a723a76bbe)
![screenshot-1](https://github.com/HASwitchPlate/openHASP/assets/5354495/0f356566-123c-43cd-8a70-62136252341f)
![screenshot-2](https://github.com/HASwitchPlate/openHASP/assets/5354495/c63c2055-39b5-42be-b792-b6265b5da94d)
![screenshot-3](https://github.com/HASwitchPlate/openHASP/assets/5354495/ff451617-af39-46ed-802a-24e102607c17)
![screenshot-4](https://github.com/HASwitchPlate/openHASP/assets/5354495/777c15cd-a4fb-4445-aabf-4986f4a62fce)

**Comment by Suschibomber** [comment] 2024-04-11 08:49
@TNTLarsn 

Hey, that looks great. Great work and many thanks for your answer.
I have posted it in a German forum. That would be the easiest place for me to continue writing :)

https://community.simon42.com/t/planung-und-einrichtung-esp32-s3-4848s040-480-480-ips-touchscreen/22943

Otherwise I have also opened a topic here.

https://community.home-assistant.io/t/planning-and-setup-esp32-s3-4848s040-480-480-ips-touchscreen/715781

**Comment by Suschibomber** [comment] 2024-04-18 21:49
Someone has the GPIO Pins for the 3 Relay Version for me?

**Comment by smcgann99** [comment] 2024-04-26 15:23
gpio 1 2 and 40

**Comment by fvanroie** [comment] 2024-04-26 17:26
If someone wants to add a page for this device to the documentation that would be great.

**Comment by enjoy-development** [comment] 2024-12-24 11:25
for the EU there is maybe a good solution for Wallmount (OBI Hardware Store) 
Simmilar to this https://www.obi.de/p/1820364/abzweigkasten-unterputz-80-mm-x-80-mm-x-50-mm
1-2€  
https://budvillgmbh.de/produkte/unterputz-verbindungskasten-80x80mm/
![AK1_FRONT_120](https://github.com/user-attachments/assets/700bfcf2-43e9-40a5-9141-164a6417646a)
There are four screwholes
![WhatsApp Bild 2024-12-24 um 12 17 27_aea157da](https://github.com/user-attachments/assets/3b3da130-1a14-4f31-bd7c-83ae3e3cebcd)
four holes measured and drilled and the screw heads countersunk a little
![WhatsApp Bild 2024-12-24 um 12 15 10_469dd4b9](https://github.com/user-attachments/assets/3743d5b9-c064-4b61-8303-8ff871babf14)
ok, we need two new small holes instead of the regular two, but fits very well
![WhatsApp Bild 2024-12-24 um 12 15 10_33f3452d](https://github.com/user-attachments/assets/4be74d32-73c7-44c5-9c01-6f00acbd5fc6)

**Comment by Suschibomber** [comment] 2024-12-24 12:10
Yes, cool. I'm also from Germany, but I just ordered the matching flush-mounted boxes from Ali for an apple and an egg 🤗 But it's good to know that it works with it too.

**Comment by MarceloSobral-Quallit** [comment] 2025-04-15 03:36
> I also have one of these and i managed to setup the pin configuration for the Display. I got the pin mappings out of the `1-Demo/Demo_Arduino/1_1_86switch_onoff/86switch_onoff/86switch_onoff.ino` sketch provided with the units documentation.
> 
> Everything seems to work except the colors. ![image](https://github.com/HASwitchPlate/openHASP/assets/46108034/8b4712ca-8b57-4312-aa98-551f1cc27b18) ![expected-1](https://github.com/HASwitchPlate/openHASP/assets/46108034/c57ad916-c3de-4078-ad85-44ed101b42fa)
> 
> ![testimage-image](https://github.com/HASwitchPlate/openHASP/assets/46108034/1ae1bad8-8ed8-4576-8643-b95965bdea82) ![expected-2](https://github.com/HASwitchPlate/openHASP/assets/46108034/93efce26-f91f-449a-bc93-c593f1c9b3e2)

Dear tbxMb
Could you help me by explaining how you managed to setup the Arduino so that it would be possible to make something appear on the screen?
Thanks

**Comment by tbxMb** [comment] 2025-04-15 05:42
@MarceloSobral-Quallit   
  
If I’m not mistaken, I initially looked at the demo files provided with the display: 

1-Demo/Demo_Arduino/1_1_86switch_onoff/86switch_onoff/86switch_onoff.ino

I then modified the config for the GS-T3E v2.3 using the pin mappings I found in the demo files. 

This worked, but the colors were incorrect.

To fix this, I copied the initialization sequence sent to the display at startup from the demo as well, and added the command to invert the colors to that sequence.

I hope this helps you!

**Comment by rtofvnt** [comment] 2025-11-13 09:23
> Sensor connected locally to ESP32-4848S040 - DS18B20,AHT20,BMP280 are working
> 
> ![ESP32_view1](https://github.com/HASwitchPlate/openHASP/assets/11538048/721b5a04-8a78-4e35-b028-503a707a480c)

Hi, 
how did you connect one wire sensor ?

**Comment by flexiti** [comment] 2025-11-13 15:31
https://github.com/HASwitchPlate/openHASP/discussions/664
