### ISSUE TITLE
"btn_pos":3 and "btn_pos":4 brick of the device.

### ISSUE THREAD

**Issue by darkman7hr** [HASwitchPlate/openHASP#594] opened 2023-12-15 20:20 UTC
Saving this to pages.jsonl will brick device.

```
{"page":1,"id":14,"obj":"tabview","btn_pos":3,"x":0}
{"page":1,"id":51,"obj":"tab","parentid":14,"text":"Tab 1"}
{"page":1,"id":52,"obj":"tab","parentid":14,"text":"Tab 2"}
{"page":1,"id":53,"obj":"tab","parentid":14,"text":"Tab 3"}
{"page":1,"id":61,"obj":"switch","x":20,"y":10,"w":60,"h":30,"parentid":51,"radius":25,"radius20":25}
{"page":1,"id":71,"obj":"dropdown","x":15,"y":10,"w":110,"h":30,"parentid":52,"options":"Apple\nBanana\nOrange\nMelon"}
{"page":1,"id":81,"obj":"checkbox","x":15,"y":10,"w":110,"h":30,"parentid":53,"text":" Nice tabview"}
```

**Comment by fvanroie** [comment] 2023-12-15 23:30
Duplicate of #509

**Closed by fvanroie** 2023-12-15 23:30 UTC
Labels: bug
